### ISSUE TITLE
Change the title of the repo

### ISSUE THREAD

**Issue by arka-g** [k-dang/Edulyitics#6]
This looks ugly. Let's put a better description there of what we're doing.
Also, we should make this repo private. Oh and while you're at it, rename it to "Edulytics".

I think only the creator of the repo can do both these things @k-dang 

![screen shot 2015-06-28 at 11 22 30 am](https://cloud.githubusercontent.com/assets/3720814/8396922/1bdaa6d6-1d88-11e5-8f69-310464c67bc7.png)

**Comment by k-dang** [comment]
I think I need to upgrade my membership for private repos

**Comment by S-Berhane** [comment]
students get free premium membership, which comes with 5 private repos i think

**Comment by k-dang** [comment]
I needa sign up for the student pack, I will do it soon
